import { choice, number } from '../fields';

export const PLAYER_CONDITION_HAS_EFFECT = () => ({
  __key: 'skilltree:has_effect',
  type: 'skilltree:has_effect',
  amplifier: number(0),
  effect: choice('skilltree:poison', [
    'absorption',
    'bad_luck',
    'bad_omen',
    'blindness',
    'conduit_power',
    'critical_damage',
    'damage',
    'darkness',
    'dolphins_grace',
    'fire_resistance',
    'glowing',
    'haste',
    'health_boost',
    'hero_of_the_village',
    'hunger',
    'instant_damage',
    'instant_health',
    'invisibility',
    'jump_boost',
    'levitation',
    'life_regeneration_luck',
    'mining_fatigue',
    'nausea',
    'night_vision',
    'poison',
    'regeneration',
    'resistance',
    'saturation',
    'slow_falling',
    'slowness',
    'speed',
    'strength',
    'water_breathing',
    'weakness',
    'wither',
  ]),
});
